# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addEditCoffeeForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dialog(object):
    def setupUi(self, dialog):
        dialog.setObjectName("dialog")
        dialog.resize(199, 300)
        self.nameEdit = QtWidgets.QLineEdit(dialog)
        self.nameEdit.setGeometry(QtCore.QRect(10, 10, 113, 20))
        self.nameEdit.setObjectName("nameEdit")
        self.roastDegreeEdit = QtWidgets.QLineEdit(dialog)
        self.roastDegreeEdit.setGeometry(QtCore.QRect(10, 40, 113, 20))
        self.roastDegreeEdit.setObjectName("roastDegreeEdit")
        self.descriptionEdit = QtWidgets.QLineEdit(dialog)
        self.descriptionEdit.setGeometry(QtCore.QRect(10, 100, 113, 20))
        self.descriptionEdit.setObjectName("descriptionEdit")
        self.priceEdit = QtWidgets.QDoubleSpinBox(dialog)
        self.priceEdit.setGeometry(QtCore.QRect(10, 130, 111, 22))
        self.priceEdit.setMaximum(1000.0)
        self.priceEdit.setProperty("value", 0.0)
        self.priceEdit.setObjectName("priceEdit")
        self.label = QtWidgets.QLabel(dialog)
        self.label.setGeometry(QtCore.QRect(130, 130, 51, 20))
        self.label.setObjectName("label")
        self.packageSizeEdit = QtWidgets.QLineEdit(dialog)
        self.packageSizeEdit.setGeometry(QtCore.QRect(10, 160, 113, 20))
        self.packageSizeEdit.setObjectName("packageSizeEdit")
        self.saveButton = QtWidgets.QPushButton(dialog)
        self.saveButton.setGeometry(QtCore.QRect(10, 200, 171, 81))
        self.saveButton.setObjectName("saveButton")
        self.groundOrBeansEdit = QtWidgets.QLineEdit(dialog)
        self.groundOrBeansEdit.setGeometry(QtCore.QRect(10, 70, 113, 20))
        self.groundOrBeansEdit.setObjectName("groundOrBeansEdit")

        self.retranslateUi(dialog)
        QtCore.QMetaObject.connectSlotsByName(dialog)

    def retranslateUi(self, dialog):
        _translate = QtCore.QCoreApplication.translate
        dialog.setWindowTitle(_translate("dialog", "Добавить/редактировать кофе"))
        self.nameEdit.setPlaceholderText(_translate("dialog", "Название сорта"))
        self.roastDegreeEdit.setPlaceholderText(_translate("dialog", "Степень обжарки"))
        self.descriptionEdit.setPlaceholderText(_translate("dialog", "Описание вкуса"))
        self.label.setText(_translate("dialog", "Цена"))
        self.packageSizeEdit.setPlaceholderText(_translate("dialog", "Объем упаковки"))
        self.saveButton.setText(_translate("dialog", "Сохранить"))
        self.groundOrBeansEdit.setPlaceholderText(_translate("dialog", "Молотый/в зернах"))
